/*
 * This file is generated by jOOQ.
 */
package com.veronica.atheticaprobyveronica.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.veronica.atheticaprobyveronica.tables.Categoria;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CategoriaRecord extends UpdatableRecordImpl<CategoriaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AthleticProByVeronica.Categoria.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Categoria.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Categoria.Nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Categoria.Nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Categoria.Descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Categoria.Descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoriaRecord
     */
    public CategoriaRecord() {
        super(Categoria.CATEGORIA);
    }

    /**
     * Create a detached, initialised CategoriaRecord
     */
    public CategoriaRecord(Integer id, String nombre, String descripcion) {
        super(Categoria.CATEGORIA);

        setId(id);
        setNombre(nombre);
        setDescripcion(descripcion);
        resetChangedOnNotNull();
    }
}
