/*
 * This file is generated by jOOQ.
 */
package com.veronica.atheticaprobyveronica.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.veronica.atheticaprobyveronica.tables.Factura;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FacturaRecord extends UpdatableRecordImpl<FacturaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AthleticProByVeronica.Factura.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.Fecha</code>.
     */
    public void setFecha(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.Fecha</code>.
     */
    public LocalDateTime getFecha() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.IdUsuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.IdUsuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.MetodoPago</code>.
     */
    public void setMetodopago(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.MetodoPago</code>.
     */
    public String getMetodopago() {
        return (String) get(3);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.MontoPagado</code>.
     */
    public void setMontopagado(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.MontoPagado</code>.
     */
    public BigDecimal getMontopagado() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.PrecioNeto</code>.
     */
    public void setPrecioneto(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.PrecioNeto</code>.
     */
    public BigDecimal getPrecioneto() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.Descuento</code>.
     */
    public void setDescuento(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.Descuento</code>.
     */
    public BigDecimal getDescuento() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.Impuesto</code>.
     */
    public void setImpuesto(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.Impuesto</code>.
     */
    public BigDecimal getImpuesto() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Factura.PrecioTotal</code>.
     */
    public void setPreciototal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Factura.PrecioTotal</code>.
     */
    public BigDecimal getPreciototal() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FacturaRecord
     */
    public FacturaRecord() {
        super(Factura.FACTURA);
    }

    /**
     * Create a detached, initialised FacturaRecord
     */
    public FacturaRecord(Integer id, LocalDateTime fecha, Integer idusuario, String metodopago, BigDecimal montopagado, BigDecimal precioneto, BigDecimal descuento, BigDecimal impuesto, BigDecimal preciototal) {
        super(Factura.FACTURA);

        setId(id);
        setFecha(fecha);
        setIdusuario(idusuario);
        setMetodopago(metodopago);
        setMontopagado(montopagado);
        setPrecioneto(precioneto);
        setDescuento(descuento);
        setImpuesto(impuesto);
        setPreciototal(preciototal);
        resetChangedOnNotNull();
    }
}
