/*
 * This file is generated by jOOQ.
 */
package com.veronica.atheticaprobyveronica.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.veronica.atheticaprobyveronica.tables.Producto;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductoRecord extends UpdatableRecordImpl<ProductoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AthleticProByVeronica.Producto.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Producto.Nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.Nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Producto.Descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.Descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Producto.IdCategoria</code>.
     */
    public void setIdcategoria(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.IdCategoria</code>.
     */
    public Integer getIdcategoria() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Producto.Precio</code>.
     */
    public void setPrecio(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.Precio</code>.
     */
    public BigDecimal getPrecio() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Producto.Cantidad</code>.
     */
    public void setCantidad(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Producto.Cantidad</code>.
     */
    public Integer getCantidad() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductoRecord
     */
    public ProductoRecord() {
        super(Producto.PRODUCTO);
    }

    /**
     * Create a detached, initialised ProductoRecord
     */
    public ProductoRecord(Integer id, String nombre, String descripcion, Integer idcategoria, BigDecimal precio, Integer cantidad) {
        super(Producto.PRODUCTO);

        setId(id);
        setNombre(nombre);
        setDescripcion(descripcion);
        setIdcategoria(idcategoria);
        setPrecio(precio);
        setCantidad(cantidad);
        resetChangedOnNotNull();
    }
}
