/*
 * This file is generated by jOOQ.
 */
package com.veronica.modelo;


import com.veronica.modelo.tables.Categoria;
import com.veronica.modelo.tables.Factura;
import com.veronica.modelo.tables.Permiso;
import com.veronica.modelo.tables.Producto;
import com.veronica.modelo.tables.Usuario;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Athleticprobyveronica extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>AthleticProByVeronica</code>
     */
    public static final Athleticprobyveronica ATHLETICPROBYVERONICA = new Athleticprobyveronica();

    /**
     * The table <code>AthleticProByVeronica.Categoria</code>.
     */
    public final Categoria CATEGORIA = Categoria.CATEGORIA;

    /**
     * The table <code>AthleticProByVeronica.Factura</code>.
     */
    public final Factura FACTURA = Factura.FACTURA;

    /**
     * The table <code>AthleticProByVeronica.Permiso</code>.
     */
    public final Permiso PERMISO = Permiso.PERMISO;

    /**
     * The table <code>AthleticProByVeronica.Producto</code>.
     */
    public final Producto PRODUCTO = Producto.PRODUCTO;

    /**
     * The table <code>AthleticProByVeronica.Usuario</code>.
     */
    public final Usuario USUARIO = Usuario.USUARIO;

    /**
     * No further instances allowed
     */
    private Athleticprobyveronica() {
        super("AthleticProByVeronica", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categoria.CATEGORIA,
            Factura.FACTURA,
            Permiso.PERMISO,
            Producto.PRODUCTO,
            Usuario.USUARIO
        );
    }
}
