/*
 * This file is generated by jOOQ.
 */
package com.veronica.modelo.tables.records;


import com.veronica.modelo.tables.Permiso;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermisoRecord extends UpdatableRecordImpl<PermisoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AthleticProByVeronica.Permiso.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Permiso.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Permiso.Nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Permiso.Nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermisoRecord
     */
    public PermisoRecord() {
        super(Permiso.PERMISO);
    }

    /**
     * Create a detached, initialised PermisoRecord
     */
    public PermisoRecord(Integer id, String nombre) {
        super(Permiso.PERMISO);

        setId(id);
        setNombre(nombre);
        resetChangedOnNotNull();
    }
}
