/*
 * This file is generated by jOOQ.
 */
package com.veronica.modelo.tables.records;


import com.veronica.modelo.tables.Usuario;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Cedula</code>.
     */
    public void setCedula(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Cedula</code>.
     */
    public String getCedula() {
        return (String) get(1);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Nombre</code>.
     */
    public void setNombre(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Nombre</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Correo</code>.
     */
    public void setCorreo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Correo</code>.
     */
    public String getCorreo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Contraseña</code>.
     */
    public void setContraseña(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Contraseña</code>.
     */
    public String getContraseña() {
        return (String) get(4);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.IdPermiso</code>.
     */
    public void setIdpermiso(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.IdPermiso</code>.
     */
    public Integer getIdpermiso() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Telefono</code>.
     */
    public void setTelefono(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Telefono</code>.
     */
    public String getTelefono() {
        return (String) get(6);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Direccion</code>.
     */
    public void setDireccion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Direccion</code>.
     */
    public String getDireccion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>AthleticProByVeronica.Usuario.Activo</code>.
     */
    public void setActivo(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>AthleticProByVeronica.Usuario.Activo</code>.
     */
    public Boolean getActivo() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioRecord
     */
    public UsuarioRecord() {
        super(Usuario.USUARIO);
    }

    /**
     * Create a detached, initialised UsuarioRecord
     */
    public UsuarioRecord(Integer id, String cedula, String nombre, String correo, String contraseña, Integer idpermiso, String telefono, String direccion, Boolean activo) {
        super(Usuario.USUARIO);

        setId(id);
        setCedula(cedula);
        setNombre(nombre);
        setCorreo(correo);
        setContraseña(contraseña);
        setIdpermiso(idpermiso);
        setTelefono(telefono);
        setDireccion(direccion);
        setActivo(activo);
        resetChangedOnNotNull();
    }
}
