/*
 * This file is generated by jOOQ.
 */
package com.veronica.atheticaprobyveronica.models;


import com.veronica.atheticaprobyveronica.tables.Categoria;
import com.veronica.atheticaprobyveronica.tables.Factura;
import com.veronica.atheticaprobyveronica.tables.Permiso;
import com.veronica.atheticaprobyveronica.tables.Producto;
import com.veronica.atheticaprobyveronica.tables.Usuario;


/**
 * Convenience access to all tables in AthleticProByVeronica.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>AthleticProByVeronica.Categoria</code>.
     */
    public static final Categoria CATEGORIA = Categoria.CATEGORIA;

    /**
     * The table <code>AthleticProByVeronica.Factura</code>.
     */
    public static final Factura FACTURA = Factura.FACTURA;

    /**
     * The table <code>AthleticProByVeronica.Permiso</code>.
     */
    public static final Permiso PERMISO = Permiso.PERMISO;

    /**
     * The table <code>AthleticProByVeronica.Producto</code>.
     */
    public static final Producto PRODUCTO = Producto.PRODUCTO;

    /**
     * The table <code>AthleticProByVeronica.Usuario</code>.
     */
    public static final Usuario USUARIO = Usuario.USUARIO;
}
